namespace: derekwaters
name: opa
version: 1.0.0
readme: README.md
authors:
- Derek Waters <derek@frisbeeworld.com>

description: A collection for managing the OpenPolicyAgent service

license_file: 'LICENSE'
tags:
  - opa
  - openpolicyagent
  - policy

dependencies: {}
repository: https://github.com/derekwaters/opa_collection
issues: https://github.com/derekwaters/opa_collection/issues
