---
#   opa_host
#   opa_port
#   opa_policy_namespace
#   opa_policy_rule
#   opa_input_data
# Output:
#   opa_query_result
- ansible.builtin.include_tasks: "pre-check.yml"
- ansible.builtin.include_tasks: "query.yml"
  