galaxy_info:
  author: Derek Waters
  description: This role allows you to create, update and manage policies in an OpenPolicyAgent (OPA) Server
  company: frisbeeworld

  license: GPL-3.0

  min_ansible_version: 2.1

  galaxy_tags: 
    - opa
    - policy
    - policies
    - policyascode
    - OpenPolicyAgent

dependencies: []
