---
# 'config' role to check the config of the OPA server

ansible.builtin.assert:
  that:
    - opa_host is defined
    - opa_port is defined

ansible.builtin.set_fact:
  __opa_status_uri: "{{ opa_host }}:{{ opa_port }}/v1/config"


ansible.builtin.uri:
  url: "{{ __opa_status_uri }}"
  return_content: true
  body_format: json
register: __opa_config

ansible.builtin.debug:
  var: __opa_config