---
- name: Stop the OPA systemd service
  ansible.builtin.systemd_service:
    state: stopped
    daemon_reload: true
    name: opa

- name: Remove OPA systemd unit configuration
  ansible.builtin.file:
    path: /etc/containers/systemd/opa.container
    state: absent
  become: true
